server:               "Thinagar"
driver:               "{ODBC Driver 17 for SQL Server}"
database:             "KAGGLE"
schema:               "COVID_19_INDIA"

db_admin:
  username:           "admin"
  password:           "Thinagar3821@"
  default_database:    "master"

db_user:
  username:           "naga"
  password:           "Thinagar3821@"